services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend  # Path to your Dockerfile
    container_name: react_frontend_menu
    ports:
      - "5173:5173"  # Map container port to host port
    volumes:
      - ./frontend:/app  # Bind mount the frontend directory to the container
      - /app/node_modules  # Optional: Prevent the host from using the container's node_modules
    command: ["yarn", "dev"]  # Start the Vite development server
    environment:
      NODE_ENV: development
      VITE_FETCH_API: "http://localhost:3000"
    networks:
      - my_network

networks:
  my_network:
